version: '3'
services:
  php73_nginx:
    image: php73_nginx
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - VIRTUAL_HOST=localhost
      - PHP_IDE_CONFIG=serverName=localhost
    ports:
      - "80:80"
    volumes:
      -  ./:/var/www
      -  ./docker/etc/php/7.3/mods-available/xdebug.ini:/etc/php/7.3/mods-available/xdebug.ini
      -  ./docker/tmp/xdebug/:/tmp/xdebug
      -  ./docker/etc/nginx/sites-enabled:/etc/nginx/sites-enabled
      -  ./docker/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network
  mysql:
    image: mysql:5.7
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=path_demo
      - MYSQL_ROOT_PASSWORD=F3hC8DxmCf5Juyyr
    ports:
      - '3306:3306'
    volumes:
      - ../docker/var/lib/mysql2:/var/lib/mysql
    networks:
      - app-network
#Docker Networks
networks:
  app-network:
    driver: bridge
